package dev.mike.couchtour

import android.content.Context
import android.util.Log
import kotlinx.serialization.json.Json

/**
 * Static heuristic matches generated by the offline `generate_heuristic_matches.py` script.
 * These are date+venue matches between phish.in/Relisten shows and official Spotify/Tidal
 * releases, produced with a strict 0% false-positive threshold. Loaded once at startup,
 * same pattern as [CuratedMatches], and consulted only when no curated match exists.
 *
 * Every entry in the JSON carries `isHeuristic: true`, so the UI can display a confidence
 * indicator distinguishing these automated matches from hand-curated ones (D258).
 */
object HeuristicMatches {
    private var mappings: Map<String, ExternalRelease> = emptyMap()

    fun init(context: Context) {
        runCatching {
            val jsonStr = context.assets.open("heuristic_matches.json").bufferedReader().use { it.readText() }
            val format = Json { ignoreUnknownKeys = true }
            mappings = format.decodeFromString(jsonStr)
        }.onFailure { e ->
            Log.e("HeuristicMatches", "Failed to load heuristic matches", e)
        }
    }

    fun match(backend: Backend, artistId: String, date: String): ExternalRelease? {
        return mappings["${backend.id}:$artistId:$date"]
    }
}
