import Foundation

/// Static heuristic matches generated by the offline `generate_heuristic_matches.py` script.
/// These are date+venue matches between phish.in/Relisten shows and official Spotify/Tidal
/// releases, produced with a strict 0% false-positive threshold. Loaded once at startup,
/// same pattern as ``CuratedMatches``, and consulted only when no curated match exists.
///
/// Every entry in the JSON carries `isHeuristic: true`, so the UI can display a confidence
/// indicator distinguishing these automated matches from hand-curated ones (D258).
public struct HeuristicMatches: Sendable {
    public static let shared = HeuristicMatches()
    
    private let mappings: [String: ExternalRelease]
    
    private init() {
        if let url = Bundle.module.url(forResource: "heuristic_matches", withExtension: "json"),
           let data = try? Data(contentsOf: url),
           let decoded = try? JSONDecoder().decode([String: ExternalRelease].self, from: data) {
            self.mappings = decoded
        } else {
            self.mappings = [:]
        }
    }
    
    public func match(backend: Backend, artistId: String, date: String) -> ExternalRelease? {
        let key = "\(backend.rawValue):\(artistId):\(date)"
        return mappings[key]
    }
}
